/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sign(header: JwtHeader, payload: any, secret: string): string
export interface JwtHeader {
  alg: JwtAlgorithm
  cty?: string | undefined | null
  jku?: string | undefined | null
  kid?: string | undefined | null
  typ?: string | undefined | null
  x5U?: string | undefined | null
  x5C?: Array<string> | undefined | null
  x5T?: string | undefined | null
  x5TS256?: string | undefined | null
}
export const enum JwtAlgorithm {
  HS256 = 0,
  HS384 = 1,
  HS512 = 2,
  ES256 = 3,
  ES384 = 4,
  RS256 = 5,
  RS384 = 6,
  RS512 = 7,
  PS256 = 8,
  PS384 = 9,
  PS512 = 10,
  EdDSA = 11
}
export interface VerifyOptions {
  requiredSpecClaims?: Array<string> | undefined | null
  leeway: number
  validateExp: boolean
  validateNbf: boolean
  aud?: string | undefined | null
  iss?: string | undefined | null
  sub?: string | undefined | null
  alg: JwtAlgorithm
}
export interface Decoded {
  header: JwtHeader
  claims: any
}
export function verify(token: string, secret: string, options: VerifyOptions): Decoded
export function sum(a: number, b: number): number
